export const NOTATION_CONFIG = {
  fdi: {
    name: 'fdi',
    index: 0,
    list: [
      18,
      17,
      16,
      15,
      14,
      13,
      12,
      11,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      38,
      37,
      36,
      35,
      34,
      33,
      32,
      31,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
    ],
  },
  universal: {
    name: 'universal',
    index: 1,
    list: [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
    ],
  },
  palmer: {
    name: 'palmer',
    index: 2,
    list: [
      8,
      7,
      6,
      5,
      4,
      3,
      2,
      1,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      8,
      7,
      6,
      5,
      4,
      3,
      2,
      1,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
    ],
  },
};

export const mapper = {
  companyName: 'companyName',
  sender: 'Owner',
  receiver: 'Partner',
  model: {
    teeth: {
      config: NOTATION_CONFIG,
    },
  },

  user: {
    owner: {
      id: 1,
    },
    partner: {
      id: 2,
    },
  },
  ceo: {
    index: 'ceo',
    text: 'CEO',
  },
  manager: {
    index: 'manager',
    text: 'Manager',
  },
  language: {
    defs: {
      kr: {
        id: 1,
        label: 'Korean',
        index: 'KR',
      },
      en: {
        id: 2,
        label: 'English',
        index: 'EN',
      },
    },
    use: {
      useArray: [1, 2],
    },
  },
  visibilityType: {
    defs: {
      public: {
        id: 0,
        label: 'Public',
        index: 'public',
      },
      partnerShip: {
        id: 1,
        label: 'Public to Partners',
        index: 'partnerShip',
      },
      private: {
        id: 2,
        label: 'Private',
        index: 'private',
      },
    },
    use: {
      useArray: [0, 1],
    },
  },
  pageUrl: {
    index: '/',
    login: '/auth/signin',
    signUp: '/auth/signup',
    resetPassword: '/auth/reset/password',
    logout: '/auth/logout',
    project: {
      index: '/project',
      list: '/project/list',
      detail: '/project/detail',
    },
    mypage: {
      index: '/mypage',
      information: '/mypage/infomation',
      partners: '/mypage/partners',
      product: '/mypage/product',
      option: '/mypage/option',
    },
    store: {
      index: '/store',
      sync: '/store/sync',
      app: '/store/app',
      invoice: '/store/invoice',
    },
    error: {
      index: '/error',
      server: '/error/500',
      notFound: '/error/404',
    },
  },
  companyType: {
    defs: {
      clinic: {
        id: 1,
        label: 'Clinic',
        index: 'clinic',
      },
      lab: {
        id: 2,
        label: 'CAD Lab',
        index: 'lab',
      },
      milling: {
        id: 3,
        label: 'Milling center',
        index: 'milling',
      },
      designer: {
        id: 4,
        label: 'Designer',
        index: 'designer',
      },
    },
    use: {
      useArray: [1, 2, 3, 4],
    },
  },
  partnerSearchType: {
    defs: {
      all: {
        id: 0,
        label: 'All',
        index: 'all',
      },
      base: {
        id: 1,
        label: 'Unique Code',
        index: 'userCode',
      },
      company: {
        id: 2,
        label: 'Office Name',
        index: 'companyName',
      },
      manager: {
        id: 3,
        label: 'CEO Name',
        index: 'manager',
      },
      address: {
        id: 4,
        label: 'Address',
        index: 'address',
      },
    },
    use: {
      useArray: [0, 1, 2, 3, 4],
    },
  },
};
